version: "2"
services:
  apostrophe:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data/uploads:/app/public/uploads
      - ./data/backups:/app/backups
    environment:
      - APOS_MONGODB_URI=mongodb+srv://admin:dope@cluster0.axqsx.mongodb.net/db
